### ISSUE TITLE
Keepass 2 crashes with keepassnatmsg + KeePassXC-browser update

### ISSUE THREAD

**Issue by Gobo42** [smorks/keepassnatmsg#100]
I just started using KeePass 2 with keepassnatmsg and KeePassXC-Browser, so it's all the latest versions. I am finding that when I update a password and KeePassXC-Browser tries to create a new password or update an existing one, the first works, but all subsequent pushes into the database, KeePass crashes and looses all the new passwords I made.

I'm not even sure where to pull debug logs or how to generate debug logs to figure out whats going on. Can someone help? Is this replicable or is there a way I can pull the equivalent of a support package?

Thanks.

**Comment by smorks** [comment]
sorry for the delay in responding to this. i don't believe there's an easy way for you to debug this yourself without building the dll yourself.

i will hopefully be able to look into this further soon. i'll let you know what i find.

**Comment by Gobo42** [comment]
I was able to get the crashes to stop. I didn't download KeePassNatMsg-kp2.45.plgx and only KeePassNatMsg.plgx. I installed the other one and crashes stopped at least. I know it seems obvious now, but maybe a note in the readme/installation notes explaining the difference between the two?
I wish there was a way to generate logs so I knew what was going on.

Thanks anyway.
