### ISSUE TITLE
Saving Keys not made database unsaved

### ISSUE THREAD

**Issue by amuagarwal** [smorks/keepassnatmsg#105]
when connecting via browser and give the key name. the database not show the changes that it need to save the changes because of this keepass not give any error on exit nor save the database and in next open there is no link keys found

**Comment by smorks** [comment]
thanks for your bug report. this issue has been fixed (c60c9f1a5a2e697ad0755da32965c7664e177b3e), although it hasn't been released yet. i will try and get a new release out this weekend.

**Comment by amuagarwal** [comment]
hope this change will fix the same issue when user click delete key or delete all keys?

**Comment by smorks** [comment]
I will double check that before making a release.
