### ISSUE TITLE
Installing on Arch

### ISSUE THREAD

**Issue by metzger100** [smorks/keepassnatmsg#106]
I am failing on the Point:
Install/Update Native Messaging Host

It doesn't install the Host. If I select Firefox it says, that the install was completely successfully but it doesn't change the state on the Native Messaging Status. 

I am using Arch Linux with KDE Plasma. 

If you need more infos or logs, I am willing to provide them, but you have to tell me how. I am pretty new to Arch linux. 

I istalled the mono package with pacman so mono should be working. 

Greetings Metzger

**Comment by smorks** [comment]
it should be creating a file called `~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json`

and the content should look similar to:

```json
{
  "name": "org.keepassxc.keepassxc_browser",
  "description": "KeepassXC integration with Firefox with Native Messaging support",
  "path" : "/home/<username>/.keepassnatmsg/run-proxy.sh",
  "type": "stdio",
  "allowed_extensions": [
    "keepassxc-browser@keepassxc.org"
  ]
}
```

and you should also see two files in `~/.keepassnatmsg`: 
keepassnatmsg-proxy.exe
run-proxy.sh

one reason that this may not work properly is that if you're also running KeePassXC, then it will overwrite the above .json file if browser integration is on as well. not sure why else it wouldn't be working? you could try deleting the .json file and deleting the `~/.keepassnatmsg` directory, and see if it re-creates them when you click on Install?

**Comment by metzger100** [comment]
I got it working by manually moving the Plugin into the plugin-folder instead of using the AUR-Package. Now the only Problem is, that I can't connect the KeePassXC-Chrome Plugin with KeePass but I will figure that out. Thanks for your Support. The Files are where they should be.
