### ISSUE TITLE
I cannot successfully install the Native Messaging HOST due to an SSL error on Proxy

### ISSUE THREAD

**Issue by 9strands** [smorks/keepassnatmsg#11]
Following the install instructions, I receive this response from the installer:

![screenshot_20180306_095004](https://user-images.githubusercontent.com/12106718/37004219-cb3755ec-2123-11e8-8f31-3963271bbad8.png)

What do I need to do to resolve this?  Or can I install these native bits manually?

**Comment by 9strands** [comment]
Also, forgot - running 2.0.0.8beta on FC27 64-bit with KeePass v2.36 under mono

**Comment by smorks** [comment]
what version of mono are you running?

**Comment by 9strands** [comment]
4.8

$ rpm -qa | grep ^mono-
mono-zeroconf-0.9.0-22.fc27.x86_64
mono-basic-4.6-5.fc27.x86_64
mono-mvc-4.8.0-12.fc27.x86_64
mono-web-4.8.0-12.fc27.x86_64
mono-wcf-4.8.0-12.fc27.x86_64
mono-data-sqlite-4.8.0-12.fc27.x86_64
mono-extras-4.8.0-12.fc27.x86_64
mono-data-4.8.0-12.fc27.x86_64
mono-winforms-4.8.0-12.fc27.x86_64
mono-cecil-0.9.6-9.fc27.x86_64
mono-core-4.8.0-12.fc27.x86_64
mono-locale-extras-4.8.0-12.fc27.x86_64
mono-devel-4.8.0-12.fc27.x86_64
mono-addins-1.1-7.fc27.x86_64

**Comment by smorks** [comment]
i believe this is related to [github depracating tls 1.0 & 1.1](https://githubengineering.com/crypto-deprecation-notice/). maybe try this?

`export MONO_TLS_PROVIDER=btls`

found here: http://www.mono-project.com/docs/about-mono/releases/4.8.0/

**Comment by 9strands** [comment]
I exported that variable and then executed KeePass - same error. But I did a little more digging - looks like Mono need to move the system certificate store into it's own.  So, I shut down KeePass, then I executed

 sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt

then I restarted keepass.  After this the installation ran without issues - no verify errors,
It does seem to run under sudo, it won't work as a normal user.

**Comment by 9strands** [comment]
Unfortunately, now KeePass won't start unless I start it under sudo - I'll raise a new issue on this one - only occurs after the KeePassNatMsg client is installed.

**Comment by compilenix** [comment]
I get / got the same error.
I'm running with the following config:

Fedora 29

```
$ rpm -qa | grep '^mono-'
mono-extras-4.8.0-12.fc28.x86_64
mono-core-4.8.0-12.fc28.x86_64
mono-mvc-4.8.0-12.fc28.x86_64
mono-data-sqlite-4.8.0-12.fc28.x86_64
mono-devel-4.8.0-12.fc28.x86_64
mono-winforms-4.8.0-12.fc28.x86_64
mono-wcf-4.8.0-12.fc28.x86_64
mono-web-4.8.0-12.fc28.x86_64
mono-data-4.8.0-12.fc28.x86_64
```

This worked fine for me: `sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt`

Starting KeePass using `sudo` is not required for me and even if i try it, keepassnatmsg does not work (via `sudo`) because it's not detecting the Native Messaging HOST in any browser despite a installation success message

**Comment by smorks** [comment]
i'll test with fedora 29 to see if i can reproduce the issue.

**Comment by 9strands** [comment]
After I installed it and rebooted, it worked fine.  I'm also running a local install of KeePass under ~/bin/KeePassX.Y where X.Y is the version.

**Comment by PhoneixS** [comment]
The `cert-sync` solution didn't fix the problem for me so I've downloaded the HOST manually.

For others who can't do it automatically here are the steps (for ubuntu):
1. Go to https://github.com/smorks/keepassnatmsg-proxy/releases/
2. Access to the latest version (for example 0.0.6).
3. Click on `keepassnatmsg-proxy.exe` to download the executable.
4. Copy it into the folder `~/.keepassnatmsg`. You're done.
