### ISSUE TITLE
Release 2.0.16 KeePassNatMsg.plgx SHA256 hash does not match description

### ISSUE THREAD

**Issue by loopism** [smorks/keepassnatmsg#110]
The SHA256 hash of the published file does not match the hash in the release notes

![SHA256](https://user-images.githubusercontent.com/7290316/225514947-89e6849b-c5a5-44c8-add3-a8ae9473c660.png)

**Comment by smorks** [comment]
i just downloaded a fresh copy and double-checked the sum, and it appears to be ok to me?

```shell
❯ sha256sum -b KeePassNatMsg.plgx
f969a1ba321648e6960f1a27661e9d07eeb8e01d6eb20f24f7adc216700f8d16 *KeePassNatMsg.plgx
```

i would suggest, on windows, try to use the powershell `Get-FileHash <Filename>` command to see if that matches?

**Comment by loopism** [comment]
My error - was checking SHA-1, not SHA256
Thanks for the quick response
