### ISSUE TITLE
Smart app Control blocks keepassnetmsg.exe

### ISSUE THREAD

**Issue by kiro5678** [smorks/keepassnatmsg#113]
When I open Chrome, smart app control blocks keepassnatmsg-proxy.exe

![Screenshot 2023-11-10 180026](https://github.com/smorks/keepassnatmsg/assets/150458125/fb94cc5b-b64b-4977-ad37-13307dae45a3)

**Comment by smorks** [comment]
is this in a corporate environment or on a personal computer?

i would guess that possibly a group policy is not allowing unsigned executables to run?

**Comment by smorks** [comment]
no response, closing issue.
