### ISSUE TITLE
Insatllation via AUR not working (/not showing)

### ISSUE THREAD

**Issue by lobneroO** [smorks/keepassnatmsg#120]
I have tried to install KeePass-NatMsg via AUR. The installation itself didn't show errors, but KeePassXC is not showing any entry for it in Tools.

The AUR installs the plugin to /usr/share/keepass/plugin rather than /usr/share/keepass/**P**lugin, but even after manually copying the file it doesn't work. Also, I'm not sure about the unzip step - do I still need to do it when installing through AUR? I tried, but it did not do anything (/work).

I have mono installed (version 6.12), I have restarted KeePassXC. Tools does not show the menu option. I'm on Arch Linux.

**Comment by smorks** [comment]
not sure if it's a typo or not, but this plugin is only compatible with KeePasss, not KeePassXC. if you are using KeePassXC, then it already has all the functionality built in. see https://keepassxc.org/docs/KeePassXC_GettingStarted#_setup_browser_integration

if you're using KeePass, what version are you running?

**Comment by lobneroO** [comment]
No, it was not a typo. I have missread something in one of the readmes, it seems. Sorry.

**Comment by smorks** [comment]
no problem!
