### ISSUE TITLE
Questions about URL matching mechanism

### ISSUE THREAD

**Issue by huajideshutiao** [smorks/keepassnatmsg#122]
Is it possible to match aaa.net and aaa.com through aaa? How should I implement this behavior? Should I fill in aaa or regular expression in the URL or custom string?

**Comment by smorks** [comment]
i think the easiest way to do this would be to turn on the "Search string fields for URL" option on in the Advanced Options screen, and to just create two Advanced string entries for aaa.net & aaa.com, called something like `URL1` and `URL2`.

It appears it also supports regex expressions by turning on that option, then naming it something with `URL` AND `Regex` in the name, then it will treat the value as a regular expression.

Hope that helps!

**Comment by huajideshutiao** [comment]
> i think the easiest way to do this would be to turn on the "Search string fields for URL" option on in the Advanced Options screen, and to just create two Advanced string entries for aaa.net & aaa.com, called something like `URL1` and `URL2`.
> 

Thank you for clarifying!
Perhaps I provided inappropriate examples, as I may encounter even stranger ones during actual use. For example, aaa-cy.net, aaa-ib.org, or cg-plus.net, sf-plus.org. 

> It appears it also supports regex expressions by turning on that option, then naming it something with `URL` AND `Regex` in the name, then it will treat the value as a regular expression.
> 

I mainly use keepass2android on my phone, and the string name it creates is kp2a_xxx. If the field value is a complete URL, it can work properly, but if the field name is kp2a_URL_regex, it cannot take effect like URL_Regex. 

If possible, could the URL matching rules be broader? For example, allowing the use of a portion of the domain name (It may be a part of a subdomain or a complete subdomain+Second level domain). After all, as a user of KP2a, I think its matching logic is quite intuitive.

**Comment by huajideshutiao** [comment]
> i think the easiest way to do this would be to turn on the "Search string fields for URL" option on in the Advanced Options screen, and to just create two Advanced string entries for aaa.net & aaa.com, called something like `URL1` and `URL2`.
> 
> It appears it also supports regex expressions by turning on that option, then naming it something with `URL` AND `Regex` in the name, then it will treat the value as a regular expression.
> 
> Hope that helps!

Thanks for the reply! Although there are some unexpected circumstances, but achieved the original goal, thank you for your help!
