### ISSUE TITLE
 Timeout or not connected to KeePassXC

### ISSUE THREAD

**Issue by agsteele** [smorks/keepassnatmsg#16]
Since moving over to the KeePassNatMsg plugin with the Firefox add-on 'KeePassXC-Browser' I keep getting periods when the add-on reports 

>  Timeout or not connected to KeePassXC

I suspect, but cannot prove, that this relates to the keepassnatmsg plug-in for KeePass in as much as I can occasionally resolve the problem by accessing the keepassnatmsg options and updating the Native Message Host. 

However, the truth is that this is a hunch and nothing more.

I just fixed it this morning by deleting the plugin, reinstalling and then updating the Native Message Host. But that was with the same versions of everything previously installed.

I could switch the KeePassXC program and not use the plugin but there are several UI things I regularly use with KeePass that XC doesn't offer.

Has anyone else any experience of this.  In an hour or two it is quite possible that all will be well again.

PlugIn Beta 10
Browser Add-on 1.0.1
KeePass 2.38
Firefox 59.0.2
Windows 10

**Comment by smorks** [comment]
if you are familiar with debugging extensions, it might be helpful to get the console log for keepassxc-browser to see if there's any helpful information there.

it would probably be best to do the following after you get the above Timeout message.

in firefox go to `about:debugging#addons`, then check "Enable add-on debugging", then scroll down and find "KeePassXC-Browser", and click the Debug button below it.

You should then get a Developer Tools window, and there may be a dialog asking you to confirm the incoming connection. Next, go to the "Console" tab in the Developer Tools window, and even just selecting all and pasting it here may be useful.

**Comment by agsteele** [comment]
AFter I started this thread I got an update for the KeePassXC Firefox add-on. I also reinstalled the NatMsg plugin for KeePass. So far the issue has not returned.

So I'll close this for now and re-open if it should return.

Thanks, as always, for your help.
