### ISSUE TITLE
Incompatible with KeePass 2.40

### ISSUE THREAD

**Issue by Dvvarf** [smorks/keepassnatmsg#18]
Current version's binaries (2.0.1) do not work with newly available KeePass 2.40 and gives the following error message:

![image](https://user-images.githubusercontent.com/692438/45931589-bc3e9980-bf78-11e8-8e74-f5e4a3d7f4e6.png)

Probably just need to recompile.

**Comment by smorks** [comment]
i tested with KeePass 2.39, 2.39.1, & 2.40.

it appears it doesn't work with 2.39, but works fine with 2.39.1 and 2.40.

so i'm not clear on which version of KeePass that you're running? The title says 2.39 but in the description you mention 2.40.

**Comment by Dvvarf** [comment]
Yeah, sorry about that, fixed.

Also it turns out it was the problem with my installation: I updated my installed version with unzipped portable version and didn't include updated KeePass.exe.config. I replace my .config file with updated one and the problem was fixed: plugin works as intended.

Thank you and sorry about that non-problem I've created.
