### ISSUE TITLE
Database unlock prompt not appearing

### ISSUE THREAD

**Issue by tfvlrue** [smorks/keepassnatmsg#2]
Hi,
I've been using KeePassHTTP-connector ever since Firefox transitioned to web extensions. I just switched over to giving KeePassNatMsg+KeePassXC-browser a try. For the most part it works great, one of the best things about the XC addon is that it detects dynamically-generated password fields like the old PassIFox addon used to.

However I've noticed that unlike KeePassHTTP, it doesn't seem to prompt KeePass to unlock the database. I'm not sure if this is the fault of the KeePassXC-browser extension or KeePassNatMsg, but since this is considered "beta" I thought I'd ask here first.

Instead of unlocking the database, it just times out:
![keepass_locked](https://user-images.githubusercontent.com/35318734/34805054-e11e3ba0-f649-11e7-85de-2d48ebf06ce8.png)

I have this option enabled:
![keepassnatmsg options](https://user-images.githubusercontent.com/35318734/34805070-f58bfcbc-f649-11e7-9a94-a4e51e5df73d.png)

Let me know if there is any more info I can provide, or if you cannot repro the issue. Not sure if this is something unique to my setup (Firefox 57.0.4, KeePass 2.38, Windows 7 x64).

Thanks,
Luke

**Comment by smorks** [comment]
i can reproduce the problem here too. thanks for reporting it!
