### ISSUE TITLE
Totp auto fill isn't working

### ISSUE THREAD

**Issue by mgabi96** [smorks/keepassnatmsg#22]
I can't use the totp filler feature of the keepassxc-browser plugin.
I don't know if it's normal or not.
I tried to add a field "KPH: {TOTP}" but that does not change anything.
It works as a string field if the totp request is on the same page as the password. But for website like Amazon it doesn't work.
Thank you for your help

I'm Using Keepass 2.4 with Keepassnatmsg plugin

**Comment by smorks** [comment]
you need the latest version of KeePassNatMsg (v2.0.3) and also the [KeeOtp](https://keepass.info/plugins.html#keeotp) plugin. Once you have those configured & working, the auto-fill should work.

if it's still not working, could you let me know what version of the keepassxc-browser plugin you're using, and i'll investigate some more.

**Comment by mgabi96** [comment]
I'm using  version 1.3.0 of Keepassxc-browser. I have the latest version of KeePassNatMsg (v2.0.3)
The automatic otp fill doesn't work with amazon, microsoft and google (didn't try another)

I tried both keeotp and trayotp plugins but the field stay empty.
In keepass (2.4.0) however the code generation works well.
If I don't check "always allow access to entries",  it does ask permission to access when I click on "fill totp" but the filling does not work either

(Also the detection of username fields doesn't work with amazon and google. It is necessary to "choose custom login field" and choose username only, then use "fill password only" for the password.)

Thank you

**Comment by mgabi96** [comment]
After checking, I have the same problem with keepassxc. So the problem isn't related to keepassnatmsg but maybe to my database or to the extension keepssxc-browser

**Comment by smorks** [comment]
i'll do some testing on this myself, but it does sound like it might be a keepassxc-browser issue, especially if you see the same behavior in keepassxc.

**Comment by dragoangel** [comment]
Not work for me as well. By:
> Once you have those configured & working, the auto-fill should work.
What you mean? I have installed KeePassNatMsg 2.0.6.0 and KeeOTP 1.3.9. I have record in DB with string field name: otp and value: key=secret. I allowed Return advanced strings fields. What I need confire else?

**Comment by smorks** [comment]
that should be all you need. then, in the field you want to fill, you right click, choose KeePasXC-Browser → Fill TOTP.

In a quick test i just did, it worked for me.

**Comment by xpac1985** [comment]
@smorks before I open a new issue - is there a chance you could support the TrayTOTP plugin too?
I've set up a few dozen 2FAs with it, and like the possibility to easily get a TOTP code from the tray icon.
It uses two fields, TOTP Seed, which contains just the key, and TOTP Settings, which contains e.g. "30;6" for 30 seconds, 6 digits.

**Comment by smorks** [comment]
@xpac1985 i'll look into what it'll take to support that plugin. thanks.

**Comment by xpac1985** [comment]
Sorry, it looked to me as if that post wasn't properly added to this conversation so I added a new issue instead... my mistake.
Thanks for looking into it.
