### ISSUE TITLE
XC Browser pestering for new version of keepassxc

### ISSUE THREAD

**Issue by agsteele** [smorks/keepassnatmsg#24]
I am using KeePass (2.41) together with  keepassnatmsg and Keepass-XCBrowser plugin with Firefox.

Over the weekend the XCBrowser plugin has begun pestering for the latest version of KeepassXC which I've never used preferring the original KeePass program.

I'm wondering if keepassnatmsg spoofs the version of KeepassXC or whether I am gradually being forced to use KeePassXC. the Firefox XC-Browser plugin reports that I have version 1.3.2 of KeePassXC installed although it is not installed at all.

**Comment by smorks** [comment]
i'll investigate this, but does it help to turn off the "Check for updates of KeePassXC:" option in the keepassxc-browser options?

**Comment by agsteele** [comment]
I did rediscover this option in the XC-Browser and it does remove the persistent prompt. Even so, it might be good to spoof the KeePassXC version number if that's possible.

**Comment by agsteele** [comment]
Thanks for the fix. Greatly appreciated...
