### ISSUE TITLE
KeePassXC-Browser asks to be associated with database every few days

### ISSUE THREAD

**Issue by antoinengu** [smorks/keepassnatmsg#25]
I believe this has started since the last update of the browser plugin on chrome (1/11/19). Roughly every day or 2, the browser plugin reports an error. When I click refresh to connect to the database, it says there is no association and I have to reconnect the database with a new key association.

**Comment by antoinengu** [comment]
checking my background page for console errors, here's what i have found.

This one seems to happen a fair amount but not sure it's related.

  | x | @ | browser-polyfill.min.js:1
-- | -- | -- | --
  | safeCallbackApply | @ | extensions::uncaught…xception_handler:27
  | handleResponse | @ | extensions::sendRequest:67

Object
message: "No tab with id: 6179."
__proto__: Object


I believe it might be one of these two.
Failed to send onMessage rejected reply Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at responseCallback (extensions::messaging:210:16)
    at F.G.then.H (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/browser-polyfill.min.js:1:8305)
F.G.then.catch.H @ browser-polyfill.min.js:1

Error in event handler for (unknown): TypeError: Cannot read property 'stack' of undefined
    at Object.keepass.updatePopup (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/background/keepass.js:1047:51)
    at onDisconnected (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/background/keepass.js:857:13)

**Comment by Skrelpoid** [comment]
I'm having the same issue. It happens for me every time I close KeePass 2.41
The Browser extension will show the following
![natmsg](https://user-images.githubusercontent.com/22478595/51593908-893eef00-1ef3-11e9-84b1-2a902d335a86.png)
I don't know if this is related, but for some reason creating a connection will create an Entry with the name KeePassHttp Settings where the key is saved

**Comment by vpontin** [comment]
I got a similar situation here: every time i open Chrome i need to (re)connect with database. If i use the same connection name it even ask for overwrite in database.

**Comment by smorks** [comment]
i'm able to reproduce this as well. hopefully i can have a fix for it soon.

**Comment by GATOQSECOMIO** [comment]
same here, with "browser integration" problem (disable). 

keepassnatmsg version : 2.0.16.0
KeePassXC-Browser version: 1.8.7
Keepass version : 2.5.4
Brave Browser : 1.52.130 Chromium: 114.0.5735.198
