### ISSUE TITLE
Proxy settings for installation

### ISSUE THREAD

**Issue by scei** [smorks/keepassnatmsg#26]
When I try to install the Native Messaging Host I get a proxy error:
![image](https://user-images.githubusercontent.com/9378320/54435399-b0b27b00-4730-11e9-9a57-bb358feaaf35.png)
I tried several proxy settings in KeePass (2.41) itself and at path level (Windows). Both didn't work.
Can you please use the same proxy as KeePass or give a possibility to enter one?
I also found no way to fake the download (putting the keepassnatmsg-proxy.exe to C:\Users\<username>\AppData\Local\KeePassNatMsg) and getting it to work behind a proxy. (I saw in the source code that you always check the version no.).

**Comment by smorks** [comment]
you should be able just to copy the proxy application manually. you also have to make sure that there is a "kpnm_<browser>.json in the same %LOCALAPPDATA%\KeePassNatMsg folder, and that the proper registry keys were created for your browser.

For example, for Chrome the registry key is at:

HKCU\Software\Google\Chrome\NativeMessagingHosts\orig.keepassxc.keepassxc_browser

And the (Default) value should be set to the corresponding kpnm_chrome.json file.

if you're still having issues after checking all of that, please let me know.

**Comment by smorks** [comment]
are you still having this issue?

**Comment by niklaswa** [comment]
Would be nice if you could implement native (custom) http proxy support. E. g. I'm on a corporate machine where the traffic from applications needs to be proxied through a http proxy.
I think I've the same issue like the creator.

**Comment by mcarbonneaux** [comment]
hi,

i've the same problem...

**Comment by mcarbonneaux** [comment]
idealy before using WebClient DownloadFile/DownloadString is to use [WebProxy.GetDefaultProxy](https://learn.microsoft.com/fr-fr/dotnet/api/system.net.webproxy.getdefaultproxy) to see if the ressource need proxy and set [Proxy](https://learn.microsoft.com/fr-fr/dotnet/api/system.net.webclient.proxy) property with WebProxy.

- https://github.com/smorks/keepassnatmsg/blob/bcf4cee3359af3e737537d4993e468db39965fda/KeePassNatMsg/NativeMessaging/NativeMessagingHost.cs#L130
- https://github.com/smorks/keepassnatmsg/blob/bcf4cee3359af3e737537d4993e468db39965fda/KeePassNatMsg/NativeMessaging/NativeMessagingHost.cs#L110

**Comment by mcarbonneaux** [comment]
and something like that to prompt credential with got 407 error

```csharp
    public static NetworkCredential GetProxyCredential(string Target, string Title)
    {
      string ProxyUsername = "";
      string ProxyPassword = "";
      var cmgr = new Credential() { Target = Target };
      if (cmgr.Load())
      {
        ProxyUsername = cmgr.Username;
        ProxyPassword = cmgr.Password;
      }
      else
      {
        var prompt = new VistaPrompt()
        {
          ShowSaveCheckBox = false,
          Target = Title + Target,
          GenericCredentials = true
        };
        prompt.ShowDialog();
        ProxyUsername = prompt.Username;
        ProxyPassword = prompt.Password;
        var oCmgrSave = new Credential()
        {
          Target = Target,
          Username = ProxyUsername,
          Password = ProxyPassword,
          PersistanceType = PersistanceType.Session
        }.Save();

      }
      return new NetworkCredential(ProxyUsername, ProxyPassword);
    }
```

**Comment by mcarbonneaux** [comment]
i had time i while do pullrequest.

**Comment by mcarbonneaux** [comment]
the use of [CredentialManagement](https://www.nuget.org/packages/CredentialManagement) is only for windows.

**Comment by sergeevabc** [comment]
> ![image](https://private-user-images.githubusercontent.com/8479023/293984507-08196ff8-b405-48fb-881f-f2cef9ad5fff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjExODQsIm5iZiI6MTcwNTc2MDg4NCwicGF0aCI6Ii84NDc5MDIzLzI5Mzk4NDUwNy0wODE5NmZmOC1iNDA1LTQ4ZmItODgxZi1mMmNlZjlhZDVmZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTQyODA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRkZjRmMWVmZWY4MjEwYzE4ODI0ZTgzZWQ2YTY2NDA1ZjAxODFlYzVlZjE5ZWYxZjVkNWQxYWY4NWZmMTkzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W6EHOkkn8aUk2bs4u50QEJQtRs99ZnM1QhDasP5R6eU)

Where is the uninstall button?

I can manually remove `C:\Users\%USERNAME%\AppData\Local\KeePassNatMsg` with `keepassnatmsg-proxy.exe` and `*.json`, but some traces will remain in the registry.

**Comment by mcarbonneaux** [comment]
> Where is the uninstall button?

yes while interesting to be abel to uninstall
