### ISSUE TITLE
"Match URL schemes" doesn't work with http:// when "Search in all opened databases" is enabled

### ISSUE THREAD

**Issue by PlqnK** [smorks/keepassnatmsg#27]
Hi!
As the title says when both `Search in all opened databases for matching entries` and `Match URL schemes` are enabled KeePassNatMsg doesn't return credentials for entries having an `http://` scheme when visiting their respective websites.

I've tried the following, when both are enabled:
- `https://` works and return entries from both databases
- `http://` doesn't work and doesn't return any entry

When only `Match URL schemes` is enabled and `Search in all opened databases for matching entries` is disabled:
- `https://` works and return entries from the "active" database
- `http://` works and return entries from the "active" database

I don't know if this bug also happens with the upstream version because I don't use multiple databases with KeePassXC, only with KeePass 2 but I could test it later if needed!

I hope I've been clear enough with my explanation, if you need more information don't hesitate to ask!

**Comment by smorks** [comment]
on first glance at the code, it looks like those two options are completely independent and shouldn't interfere with one another.

i'll do some testing and try and narrow down the problem. thanks for the report!

**Comment by PlqnK** [comment]
Alright thanks!

I've quickly tested with KeePassXC and KeePassXC-Browser in Firefox, with 2 databases and it works as exepected.

To add a little bit more information about the bug, I'm using KeePass Password Safe 2 with KeePassNatMsg plugin installed from [chocolatey ](https://chocolatey.org/) and it's connected to KeePassXC-Browser running in Google Chrome.
Because I've only tested this configuration I also don't know if the bug also happens when KeePassNatMsg is connected to KeePassXC-Browser running in Firefox.

I have both KeePassXC and KeePass PS running at the same time but KeePassXC is only connected to the plugin in Firefox and KeePass PS is only connected to the plugin in Chrome and so far it hasn't caused me any trouble, I'm not even sure if it's relevant to the bug or not.

I also wanted to add that if I disable `Match URL schemes` and enable `Search in all opened databases for matching entries` KeePassNatMsg correctly returns all the entries from all databases corresponding to the hostname of the website, it's only when both are enabled at the same time that the bug occurs.

**Comment by smorks** [comment]
thanks for the additional info. i didn't even know that there was a chocolatey package for it.

anyways, i should be able to run some quick tests in the next few days, so i'll report back then.

**Comment by smorks** [comment]
i believe i fixed the issue, i'll be releasing v2.0.5 shortly.

**Comment by PlqnK** [comment]
Whoa that was quick! Alright then I will try it at work first thing tomorrow morning and report back! Thanks a lot for your work, really appreciated!

**Comment by PlqnK** [comment]
Just got to work and tested the update. It's indeed resolved, thanks again!
