### ISSUE TITLE
Use KeePassXC-Broswer custom data instead of KeePassHTTP attributes

### ISSUE THREAD

**Issue by gyli** [smorks/keepassnatmsg#28]
KeePassXC 2.4.0 recommends to move KeePassHTTP attributes to KeePassXC-Broswer custom data, they also provide an option to move for all entries.

Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/1497

I'm using both of KeePassXC and KeePass on Windows, while I feel like it's hard and unnecessary to maintain both of KeePassHTTP attributes and KeePassXC-Broswer custom data in my db. This plugin can probably also do so, to better support both apps.

**Comment by smorks** [comment]
- [ ] switch keys to using custom data
- [ ] switch allow/deny to custom data
- [ ] migrate existing data to custom data
- [ ] add ui for managing custom data?
