### ISSUE TITLE
Cannot connect with latest version 

### ISSUE THREAD

**Issue by tfvlrue** [smorks/keepassnatmsg#3]
I gave beta 4 a try, but I cannot get KeePassXC-browser to connect to it at all. After I upgraded from beta 3, and restarted KeePass, the keepassnatmsg-proxy.exe process crashed. I deleted it and re-created it with the new version, but the browser extension still cannot connect to it at all, even after restarting Firefox. I just get a timeout error:
![keepass_cannotconnect](https://user-images.githubusercontent.com/35318734/34806252-dd60aaa6-f64f-11e7-8562-bcf9837d21fb.png)

I tried taking a look at the crash dumps, but I don't have the symbols and I haven't look into how to build/deploy it myself.

I'm going to revert to using beta 3 for now, but let me know if there is any more info I can provide.

**Comment by smorks** [comment]
with beta 4, you need to re-install the Native Messaging Host, since it was updated to use the new keepassxc-browser extension (v0.4.8 or higher). sorry, i should have noted that in the release notes.

**Comment by tfvlrue** [comment]
Oh, I think I see what happened here. Firefox's automatic update mechanism didn't recognize the new keepassxc-browser extension version for some reason, it got stuck at 0.4.5. I manually installed 0.4.8 and now beta 4 of KeepPassNatMsg works fine.
