### ISSUE TITLE
Just doesn't seem to work with Chrome, Windows

### ISSUE THREAD

**Issue by Ruud-cb** [smorks/keepassnatmsg#31]
Hi,

Re-installed windows yesterday, been using KeePassHttp extension for a while but figured I will try this one since the other one is no longer supported.

operating system & version: Windows 10 - latest
version of KeePass: 2.4.1
version of KeePassNatMsg: v2.0.5
error message (if available): none unfortunately
used clients and their versions: Chrome Version 74.0.3729.108 (Official Build) (64-bit)
URLs on which the problem occur (if available):
Here are some URL's that I am sure were working before and also have the top level domain as login page. All my URL's in KeePass include schemes.
https://insights.hotjar.com/
https://www.smartlook.com/sign/in
https://www.ups.com/lasso/login?loc=us_EN

Settings:
![image](https://user-images.githubusercontent.com/10037514/56969646-e33ff800-6b65-11e9-855b-e58f6ec8ed93.png)

Not receiving any notifications, tried restarting chrome and keepass once more didn't help.

**Comment by smorks** [comment]
Do you also have the keepassxc-browser extension installed for chrome? that is required in order to communicate with KeePassNatMsg. 

if you already have it installed, it should be giving you some sort of message about not being able to connect?

**Comment by Ruud-cb** [comment]
haha ohmygod..no I didn't, skipped right to the installation instructions. *facepalm*

**Comment by smorks** [comment]
i should probably add that step to the installation instructions, just to make things more clear.
