### ISSUE TITLE
focus problem if "Always On Top" is enabled

### ISSUE THREAD

**Issue by XtraLarge** [smorks/keepassnatmsg#33]
Hi,
I have used KeePass 2.42 since yesterday and changed from KeePassHttp to KeePassNatMsg. First: Great job!!! Especially filling Http Basic Auth with multiple entries in KeePass worked perfectly.

But, if you enable "Always On Top" and you open the "KeePassNatMsg Options" the options screen appears, gets focus, but the "Always On Top" function lays keeps over the Options screen, but the Input focus stays on the KeePassNatMsg Options screen. It's difficult to explain, the best is you try it by yourself :) 

best regards.
Willi

**Comment by smorks** [comment]
thanks for the report! i'll look into this.
