### ISSUE TITLE
KeePassXC-Browser will only work if KeePass2 is launched beforehand

### ISSUE THREAD

**Issue by asia73** [smorks/keepassnatmsg#35]
KeePassXC-Browser can only see KeePass 2 when KeePass 2 was already running before the extension started. So in order to make the extension work, I need to shut the browser down, run KeePass and then launch browser again.

**Comment by smorks** [comment]
Clicking the "Reload" button in the KeePassXC-Browser extension should fix the problem without restarting the browser.

If that isn't working for you, does it give any kind of error when clicking the Reload button?

**Comment by asia73** [comment]
I remember seeing "Reload" button but now I have only "Reopen the database" instead and "cannot decrypt message" error. Anyway both Reload and Reopen did nothing when I clicked them. If I disable/enable the extension it starts working right away.

**Comment by asia73** [comment]
And then if I close KeePass and click the toolbar icon KeepassNatmsg crashes.

**Comment by smorks** [comment]
can you tell me the versions of everything that you're using? (OS, browser, KeePassXC-Browser, KeePass, KeePassNatMsg)

I'll look into it.

**Comment by asia73** [comment]
Windows 7
Opera 60.0.3255.59
KeePassXC-Browser Version: 1.4.3
KeePass 2.41
KeePassNatMsg 0.0.6.36827

**Comment by smorks** [comment]
thanks, i'll do some testing and see what i can find.

**Comment by smorks** [comment]
the behavior i'm seeing is strange.

1. Start Browser
2. Extension says "Cannot connect..."
3. Open KeePass
4. Click "Reload"
5. Nothing appears to happen
6. Click the extesion button again, it says it's connected

so it appears that when i'm pressing "Reload", it's working, but it's just not refreshing properly. i'll look into if this is a problem with the extension or with my plugin. 

in the meantime, can you try those steps and see if you're getting the same behavior?

**Comment by smorks** [comment]
and even though the button appears to not do anything, it does start working after pressing "Reload"?

**Comment by asia73** [comment]
> and even though the button appears to not do anything, it does start working after pressing "Reload"?

yes, it does

**Comment by smorks** [comment]
i tested with KeePassXC, and it does the same thing as well, so I believe it's just a display issue with the KeePassXC-Browser extension. I see you reported the issue in their repo (keepassxreboot/keepassxc-browser#523), i'll add my findings there as well.
