### ISSUE TITLE
Not work with the version 1.5.0

### ISSUE THREAD

**Issue by Havokdan** [smorks/keepassnatmsg#39]
It does not work with the latest version of the browser extension for Keepassxc 1.5.0 browser

**Comment by smorks** [comment]
it appears to be working for me with keepassxc-browser v1.5.0 on firefox on Windows.

can you give some more details about your environment? (versions for OS, Browser, keepass, keepassnatmsg)

**Comment by Havokdan** [comment]
Opera x64 63.0.3368.94, Windows x64, KeePass 2.43, KeePassNat 2.0.6.0

**Comment by smorks** [comment]
i tested with the exact same versions of everything you listed on the following sites, and they all worked fine for me:

github.com
google.com
news.ycombinator.com

can you be more specific in what isn't working, and which website isn't working for you?

**Comment by smorks** [comment]
also - try the following to see if it helps:

1. Close all Opera windows
2. In KeePass, go to Tools → KeePassNatMsg Options
3. Click on Install/Update Native Messaging Host
4. Make sure only "Google Chrome" is checked, press Ok
5. Restart Opera, and see if it works

**Comment by Havokdan** [comment]
I reinstalled the extension again and it seems that problem has been resolved, even without me doing anything, I'm sorry for the inconvenience.

**Comment by smorks** [comment]
no problem! if you run into issues again, please let me know.

**Comment by Havokdan** [comment]
![Sem título](https://user-images.githubusercontent.com/6549729/65710082-a3bffe00-e068-11e9-9a92-12bced071e95.png)

**Comment by smorks** [comment]
what shows on the "Connected Databases" page in KeePassXC-Browser settings?

**Comment by smorks** [comment]
also - are you able to test with KeePassXC to see if you run into the same problem? it might be a problem with the KeePassXC-browser extension itself? from what i can tell, it doesn't look like they made any breaking protocol changes.

**Comment by Havokdan** [comment]
![Sem título](https://user-images.githubusercontent.com/6549729/65710774-082f8d00-e06a-11e9-8cca-7846f22fc54c.png)

**Comment by Havokdan** [comment]
> also - are you able to test with KeePassXC to see if you run into the same problem? it might be a problem with the KeePassXC-browser extension itself? from what i can tell, it doesn't look like they made any breaking protocol changes.

I will try

**Comment by smorks** [comment]
also - when exactly does that happen? (the error about "cannot decrypt message")

did you first connect it to KeePass, then it worked for a bit, then you close your browser, then it stopped working and gave you that error? or something else?

**Comment by Havokdan** [comment]
Usually I use the Kee, but whenever we went out a new version of KeepassXc-Browser, I'll check it out.
I installed the new version and gave the error message I copied above, so I created this topic, and uninstalled my browser extension, then immediately installed the extension again, without my having done nothing else, he returned to work. I closed the browser and went to take a nap, wake up again and open the browser again gave the error.
Installed Keepassxc 2.4.3 x64 now to test, continue without trace, but I have enabled the option to integrate the keepassxc browsers now I've been on, at least for now and uninstalled Keepassxc and its extension to the browser and back the only use Kee.

**Comment by smorks** [comment]
i'm not super familiar with Kee, but it could be that the browser integration is conflicting with how KeePassNatMsg communicates with KeePass?

I know for sure that both KeePassXC & KeePassNatMsg use Native Messaging to communicate with the browser extension, so for example if you have KeePassXC working, you can't use KeePassNatMsg without doing the steps listed in my previous comment (https://github.com/smorks/keepassnatmsg/issues/39#issuecomment-535551757), which will in turn break KeePassXC.

**Comment by Havokdan** [comment]
Closed KeePass to use KeePassXC when open KeePassXC came a KeeNatMsg error message and that he would need to be closed, I imagine you've seen occurred because of the conflict that you mentioned. Kee use a plugin called KeePass KeePassRPC, I'm not a programmer nor have abragente technological knowledge.

**Comment by smorks** [comment]
one last thing to check - if you go in KeePass, and open the "KeePassHttp Settings" entry in the root of your database, then go to the "Advanced" tab, and edit the public key which corresponds with the name from your browser keepassxc-browser "Connected Databases" page, do the displayed characters from the "Key" column match what's in KeePass?

**Comment by Havokdan** [comment]
I'm sorry, I did not understand the first part.

**Comment by smorks** [comment]
1. Select the root folder in KeePass
2. Double-click on "KeePassHttp Settings"
3. Click on the Advanced tab
4. Edit the "Public Key: [name]" which matches the name in the "Connected Databases" page
5. Make sure the visible characters match

![2019-09-26 13_58_24-D__data_cloud brandt tech_keepass_keepass kdbx - KeePass](https://user-images.githubusercontent.com/1030007/65717276-8a1db700-e066-11e9-8ef4-31f06fd43f68.png)

**Comment by Havokdan** [comment]
Its same

**Comment by smorks** [comment]
Another thing to try:

1. Turn on "Developer mode" in Opera Extensions page
2. For KeePassXC-Browser, click on the "Inspect views: background page" link that should appear
3. Click on the Console tab, see if any errors are in there?

You can turn off Developer mode after looking for errors.

**Comment by Havokdan** [comment]
![image](https://user-images.githubusercontent.com/6549729/65719667-a6c4e980-e07c-11e9-9296-1df874024e32.png)

**Comment by smorks** [comment]
it looks like the update check isn't working. i really have no idea why.

have you tried this in other browsers to see if it's opera-specific?

**Comment by Havokdan** [comment]
> it looks like the update check isn't working. i really have no idea why.
> 
> have you tried this in other browsers to see if it's opera-specific?
> 
> you can also try (if you haven't already) deleting the connection in the KeePassXC-Browser "Connected Databases" page and then re-connecting to see if that helps?

This problem already occurs some time, delete the key and create a new only solves the problem for a while, then reappears, may be related to some other extension, use a number to block third-party items, especially Umatrix and Origin uBlock, say so why use virtually the same extensions on all browsers (Opera, Chrome, Firefox and Vivaldi).

**Comment by smorks** [comment]
i also use uBlock Origin (with mostly the default settings) and have had no issues, so it could be a different one. i have seen issues before where other extensions were causing issues with this one.

sorry i can't be more helpful than that!

**Comment by Havokdan** [comment]
Well, I am testing the version 1.5.1 and look, only it seem, that the problem was resolved, then possibly the problem was in the extension even, again, thank you.
