### ISSUE TITLE
Warning message after unlocking database

### ISSUE THREAD

**Issue by tfvlrue** [smorks/keepassnatmsg#4]
I grabbed the latest release and tried out the automatic database unlocking with keepassxc-browser. It works, except after unlocking the database, KeePass throws up a message box:

![keepass](https://user-images.githubusercontent.com/35318734/34970160-b95d57ae-fa40-11e7-8282-b58309379690.png)

After acknowledging it, everything seems to work just fine. The KeePass database is unlocked and the browser integration works fine. I'm not really sure where the message box is coming from (beyond the keepass.exe process). Is it possible the KeePassNatMsg plugin is causing it? It just started happening with beta 5, and I've never seen it before with KeePassHttp.

Let me know if there is any other info I can provide.

Thanks,
Luke

**Comment by smorks** [comment]
i'm able to reproduce this as well. i'll look into it, it's probably something to do with how i'm requesting the database to be unlocked.
