### ISSUE TITLE
Problem saving passwords...

### ISSUE THREAD

**Issue by Havokdan** [smorks/keepassnatmsg#42]
Whenever I use the keepassxc-browser extension with this plugin to save or update a password, the program actually saves, but right after that an error message pops up, and also doesn't allow the keepassxc-browser function to ask where to save, it is an expected issue related to this plugin?
I am using Keepass 2.43, Keepassnatmsg 2.0.8 and keepassxc-browser 1.5.4.

**Comment by smorks** [comment]
yes - i was just doing some testing and found the "Default Group for Saving New Passwords" option doesn't work, as well as the "Always Ask Where To Save".

i wasn't getting an error message however. can you provide the specific error message you are getting? and does it happen when you are saving a new password vs modifying an existing one?

**Comment by Havokdan** [comment]
![Sem título](https://user-images.githubusercontent.com/6549729/72544864-e0597480-3866-11ea-9997-265c3e4329d1.png)
Translated to english with google translator:

Error! Credentials cannot be saved or updated to a closed database.

Well, of course the database is open and working normally.

**Comment by smorks** [comment]
hmmm, do you have more than one database open at all?

**Comment by Havokdan** [comment]
No, only one

**Comment by smorks** [comment]
and you're saying the credentials do actually get updated in KeePass?

i'll have to get some debugging info from you - what browser are you using?

**Comment by Havokdan** [comment]
They are saved and / or updated as long as I do not use the option to choose where to save them and even then the error message above appears. I use Opera, Vivaldi, Firefox and Chrome browsers.

**Comment by smorks** [comment]
Try saving / updating some credentials, then do the following, and hopefully it should give me some insight into what's happening. Can you also tell me what OS you are running?

For Firefox:
- Menu → Add-ons
- Click on gear icon in the top right, then select "Debug Add-ons"
- Find KeePassXC-Browser, click on the "Inspect" button
- Click on the "Console" tab, copy & paste any error messages

For Chrome:
- Menu → More Tools → Extensions
- Turn ON Developer Mode in the top right corner
- Click on the "Inspect Views background page" link
- Select "Console" tab, copy & paste any error messages

**Comment by Havokdan** [comment]
`Could not map contract ID '@mozilla.org/sharepicker;1' to CID {1201d357-8417-4926-a694-e6408fbedcf8} because no implementation of the CID is registered.
Content Security Policy: Não foi possível processar o servidor inválido 'wasm-eval'
A codificação de caracteres do documento HTML não foi declarada. O documento será exibido com texto corrompido em algumas configurações de navegadores se o documento contiver caracteres fora da faixa US-ASCII. A codificação de caracteres da página deve ser declarada no documento ou protocolo de transferência. main.html
Esta página usa a propriedade não padrão “zoom”. Considere usar calc() nos valores de propriedades relevantes, ou usar “transform” junto com “transform-origin: 0 0”. background.html
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:979:13
XMLHttpRequest síncrono não deve ser usado na thread principal devido a seus efeitos prejudiciais para a experiência de usuário. Para mais informações http://xhr.spec.whatwg.org/ lpfulllib.js:1:35316
Server public key: IlDbtbf/YZIaKMqZKauNl/YV2+cuO/QPwiOAAK5sqnA= keepass.js:606:17
Error: No content script available for this tab. keepass.js:1180:25
Error 11: Nenhum banco de dados salvo foi encontrado. 4 keepass.js:1062:13
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.
2 ExtensionContent.jsm:567:25
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
Error 12: Incorrect action`

Windows 10 x64

**Comment by Havokdan** [comment]
Now in the latest version of the extension(1.6.0), it doesn't save at all.

**Comment by Havokdan** [comment]
In the last version of Keepasxc-browser, it was saved again, but only saved in the default folder, if you change the name of the default folder, it does not work, the update function does not work, and there is no way to use the option to choose the folder too.

**Comment by creckord** [comment]
In Chrome, I get the following in the dev console:
```
Error 12: Incorrect action    keepass.js:1065
```
Setting a breakpoint there, I get the following call trace:

![screenshot_2020-05-03__01](https://user-images.githubusercontent.com/393429/80913446-f4a57c80-8d44-11ea-973c-d1dab7c72cd4.png)

Windows 10, Chrome 81.0.4044.129, KeePass 2.44, KeePassNatMsg 2.0.9, KeePassXC-Browser 1.6.3

**Comment by smorks** [comment]
thanks @creckord, that gives me a good lead. i'll look into it further soon.

**Comment by lucaspatecki** [comment]
hi, im have same problem when i try to save now password, but i found that keepasxc extension on vivaldi browser is saving my password to KeePassNatMsg Passwords folder in keepas 2.4.5 and that folder is in rycle bin :P

**Comment by smorks** [comment]
this should be fixed when #43 is done.

**Comment by Havokdan** [comment]
Yes, it returned to the previous behavior, only saved in a standard plugin folder, unfortunately it does not behave in the same way as the KeepassXC, in which you can choose, which group in the database you want to save and still, usually, ask to save twice.

**Comment by smorks** [comment]
is this still an issue? i believe it should be behaving the same as KeePassXC.
