### ISSUE TITLE
Support for KeeTrayTOTP entries

### ISSUE THREAD

**Issue by xpac1985** [smorks/keepassnatmsg#44]
In #22 @smorks mentioned that the TOTP auto fill requires KeeOtp to be installed.
I'd kindly ask for support for [KeeTrayTOTP](https://github.com/victor-rds/KeeTrayTOTP), too.
It's the successor/fork to TrayTOTP, and has comparable features to KeeOtp, but is under active development, allows copying TOTP codes via the tray icon etc.
It stores the relevant data in two extra fields, called TOTP Seed with only the key inside, and TOTP Settings with data like "30;6" inside, meaning 30 seconds, 6 digit code.

Thanks for your work on this!

**Comment by neradp** [comment]
This is not working for me on any page :(
I have installed KeeTrayTOTP only.
