### ISSUE TITLE
Allow multiple URL's for a single password entry

### ISSUE THREAD

**Issue by VinnieNZ** [smorks/keepassnatmsg#45]
Feature Request.

Would it be possible to implement extra URL's to be handled for a single password entry, probably via the "String Fields" page, similar to how KPH string entries work for additional password fields?

Something like KPURL and then the string value can be the URL.

It could hopefully then allow for regex matched URL's to be added as well.

Use case example:

HP have numerous login pages between Learner ID, channel services, partner portal, unison, passport, expert one, etc...  And I've got separate entries (using references) for all these currently, as they all seem to want different URL's for credential entry.

Would be nice to tidy all that up.

Regex use case is that there is no wildcard support, which is troublesome when using the more exact URL detection - particularly when companies tend to do odd things like:
www.website.com
ww1.website.com
ww2.website.com
www.website.net

It'd be good to be able to have the URL field as https://www.website.com and then the ability to capture the variations using regex.

**Comment by smorks** [comment]
I've actually been wondering lately if the plugin already does that, which it doesn't. And yes it is a good idea, I'll look at implementing it when I have some free time.

**Comment by seanf** [comment]
@smorks Thanks for implementing this!

Reading the code, it seems that "URL regex" fields can only contain patterns for hostnames, not the complete URL. Is that right?

With v2.0.9, I can get the extra URL fields to work, but I just can't work out the regex support. I have a field called "URL regex", but it only seems to work for basic string matching. As soon as I add regex characters (eg escaping dot as `\.`) I get nothing.

Can you please give some examples of patterns?

eg for @VinnieNZ's example:

```
www.website.com
ww1.website.com
ww2.website.com
www.website.net
```

I would have tried this pattern:

```
^ww[w12]\.website\.(com|net)$
```

But I seem to be missing something.

**Comment by seanf** [comment]
Thanks for the explanation @smorks. I'll follow #46
