### ISSUE TITLE
URL Regex search issues

### ISSUE THREAD

**Issue by smorks** [smorks/keepassnatmsg#46]
The URL Regex search will never work if the URL Regex is the only way to identify the host (see https://github.com/smorks/keepassnatmsg/issues/45#issuecomment-591935595)

Need to research some alternative options to fix this.

**Comment by Rookiestyle** [comment]
I stumbled across this issue and did not find a *perfect* way to fix it.

The only option I found was manually adding all entries to the list of candidates that contain `URL regex` fields.
This actually means to check every entry twice.

1. Directly checking whenever logon data is requested #65 
2. Filling a buffer and updating it whenever required #66

Both approaches work fine for me, I did not notice any big difference regarding required time. The non-buffered approach might be a better fit
