### ISSUE TITLE
Automatically save after modifying permissions

### ISSUE THREAD

**Issue by seanf** [smorks/keepassnatmsg#47]
When granting permission to an entry, the entry is modified (the "KeePassHttp Settings" string field), but the database is not saved, even if the KeePass option "Automatically save after modifying an entry using the entry editing dialog" is selected. It would be nice if KeePassNatMsg could (a) respect the same option, or (b) add its own option to "Automatically save after permissions are updated".

**Comment by smorks** [comment]
i don't think this will be too hard to do, either way. i'll look into it.
