### ISSUE TITLE
Add support for Lock/Unlock messages, should prompting to unlock when browser is opened

### ISSUE THREAD

**Issue by rzenv** [smorks/keepassnatmsg#48]
There should be an option to choose auto connection to keepass app while opening browser. It is very good experience if it will connect to keepass while autofilling user/pass. We can disable this auto connection to app. It can be manually do it while filling user/pass data. Because when i open browser or new tab it will ask me to unlock db. It is bad experience.

**Comment by smorks** [comment]
sorry for the delayed response. are you saying you don't like having to unlock the database when opening the browser, and you'd like the database to be auto-unlocked?

if so, that would likely be a security issue, and would completely bypass keepass security. i'm closing this issue, if i misunderstood what you are asking, please comment and i'll review it. thanks.

**Comment by rzenv** [comment]
i mean it should be triggered while autofilling username/password instead of opening browser

**Comment by smorks** [comment]
that would be something that would have to be done in the [keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser) extension.

**Comment by rzenv** [comment]
actually it has database unlock button visible while database locked so this button is not work on natmsg.

**Comment by smorks** [comment]
this has been fixed in the above commit. will have a new release soon. closing this issue.
