### ISSUE TITLE
Add support for the keepassxc-mail add-on in Thunderbird

### ISSUE THREAD

**Issue by Crazyphil** [smorks/keepassnatmsg#49]
KeePasXC-Browser doesn't work correctly for me in Thunderbird, so I decided to use the recently created [keepassxc-mail](https://github.com/kkapsner/keepassxc-mail) add-on. This currently requires some manual interaction:

- Copy the file `kpnm_firefox.json` in `%LocalAppData%\KeePassNatMsg` to `kpnm_thunderbird.json` and change the `name` and `allowed_extensions` value ([sample file](https://github.com/smorks/keepassnatmsg/files/4385571/kpnm_thunderbird.txt))
- Add a new registry key `de.kkapsner.keepassxc_mail` under `HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts` and point the `(Default)` value to the previously created file

Could you please add support for these steps in the KeePassNatMsg options dialog so that happens automatically?

Also, the add-ons author noticed a difference in behavior between how KeePassXC and KeePassNatMsg handle native messages: https://github.com/kkapsner/keepassxc-mail/issues/11#issuecomment-603937169 This may be expected behavior, but it also could be a bug in KeePassNatMsg.

**Comment by smorks** [comment]
wow i had no idea that even existed! it shouldn't be too hard to add support for that.
