### ISSUE TITLE
Locking the database through keepassxc-browser freezes KeePass

### ISSUE THREAD

**Issue by tfvlrue** [smorks/keepassnatmsg#5]
Hi again,
Not sure if this is the fault of KeePassNatMsg or not. I noticed that if you click the lock button in the keepassxc-browser extension, the KeePass process stops responding. After killing it, the keepassnatmsg-proxy process crashes. Then I have to relaunch KeePass.exe and restart Firefox for the two to communicate again.

![keepasslock](https://user-images.githubusercontent.com/35318734/35078863-59a8bfb8-fbd2-11e7-94cc-b0e42d5a8123.png)

Thanks,
Luke

**Comment by smorks** [comment]
when i pressed the button, KeePass gave me an unhandled exception. anyways, i'll look into it. thanks!
