### ISSUE TITLE
Following KeePassNatMsg's installation procedure: KeePass crashes when clicking "Tools -> KeePassNatMsg Options"

### ISSUE THREAD

**Issue by yscialom** [smorks/keepassnatmsg#51]
Title
===
Following KeePassNatMsg's [installation procedure](https://github.com/smorks/keepassnatmsg/blob/master/README.md#installation): KeePass crashes when clicking "Tools -> KeePassNatMsg Options"

Context
===
On Ubuntu 19.10, KeePass is installed from the package manager. KeePassNatMsg is downloaded and installed manually. Crash happens when accessing --- from KeePass --- the menu "Tools -> KeePassNatMsg Options".

Observed behaviour
===
A black window opens for a few seconds; KeePass crashes.

Expected behaviour
===
A window opens providing a "Install/Update Native Messaging Host" button.

Steps to reproduce
===
On Ubuntu 19.10, open a terminal:
` ` ` `0. Install KeePass: `sudo apt install -y keepass2`
Follows [KeePassNatMsg installation instructions](https://github.com/smorks/keepassnatmsg/blob/master/README.md#installation):
1. Download the latest KeePassNatMsg release 
2. Unzip it to `/usr/lib/keepass2/Plugins/`
3. Install mono `sudo apt install -y mono-complete`
4. Restart KeePass
5. Go to Tools -> KeePassNatMsg Options

Crash.

Details & Versions
===
* OS version: **Ubuntu 19.10** (`cat /etc/os-release`)
* Mono version: **5.18.0.240** (`mono --version`)
* KeePass version:  **KeePass 2.41** (`keepass2 --version`)
* KeePassNatMsg version: **2.0.9** (`KeePassNatMsg-v2.0.9-binaries.zip`)
* KeePassNatMsg files' rights:
```
yscialom@Kloe:/usr/lib/keepass2/Plugins$ ll
drwxr-xr-x 2 root root 4,0K févr. 21 22:34 KeePassNatMsg/
yscialom@Kloe:/usr/lib/keepass2/Plugins$ ll KeePassNatMsg/
-rwxr-xr-x 1 root root 105K févr. 21 22:34 KeePassNatMsg.dll
-rwxr-xr-x 1 root root  78K déc.  21  2017 Mono.Posix.dll
-rwxr-xr-x 1 root root 514K déc.  21  2017 Newtonsoft.Json.dll
```

**Comment by rengaw83** [comment]
Have the same Problem with different Setup:

- OS version: Ubuntu 18.04.4 LTS (cat /etc/os-release)
- Mono version: 6.8.0.123 (mono --version)
- KeePass version: KeePass 2.44 (keepass2 --version)
- KeePassNatMsg version: 2.0.9 (KeePassNatMsg-v2.0.9-binaries.zip)


Have started keepass with mono on terminal. 
After i clicked on "Tools -> KeePassNatMsg Options" the following error occurs:
```bash
$ mono KeePass.exe 

[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
mono: ../../src/xcb_io.c:577: _XReply: Zusicherung »!xcb_xlib_extra_reply_data_left« nicht erfüllt.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by smorks** [comment]
sorry for taking so long on this - i don't use linux an my primary os, but i'll have a look at this soon.

**Comment by smorks** [comment]
this might be a lead: kee-org/keepassrpc/issues/81

i'll do some more investigation later today.
