### ISSUE TITLE
OK I give up how to install this plugin on windows

### ISSUE THREAD

**Issue by dasb00ter** [smorks/keepassnatmsg#52]
Ok I feel silly to ask but how to get this this plugin installed in keepass. The releases are in binary format and I'm used to .pglx placed in plugins folder. I tried placing it in the plugin folder after extracting it **and** placing it in C:\Users\userredacted\AppData\Local\KeePass\PluginCache? Just gives a message that it is incompatible

**Comment by smorks** [comment]
it goes in the plugins folder, which is typically `C:\Program Files\KeePass\Plugins`.

In KeePass, you can go to Tools → Plugins → Open Folder, to open the Plugins folder.

Let me know if you have any further issues.
