### ISSUE TITLE
"No Arguments Received" popup when opening browser or refreshing extension

### ISSUE THREAD

**Issue by 9strands** [smorks/keepassnatmsg#53]
KeePassNatMsg version: 2.0.9
OS: Fedora 32 x86_64
KeePass version: 2.45 portable

Issue: after the upgrade, when I open the browser, or if I attempt to refresh the keys, I get an error window pop up from the keepassnatmsg

![image](https://user-images.githubusercontent.com/12106718/83476047-0f4d4b80-a4d3-11ea-8782-bae0f5afe1d2.png)

KeePass opens and shows the information is accessible.

I have reinstalled the native messaging hosts as well, and it seems to have no effect.

**Comment by 9strands** [comment]
From Chrome's background page for the extension:
Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1065 Error 9: Key exchange was not successful.
keepass.js:952 Failed to connect: Native host has exited.
keepass.js:1185 Error: No content script available for this tab.
keepass.js:1065 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:1065 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1065 Error 9: Key exchange was not successful.

From Firefox:
Sending message that cannot be cloned. Are you trying to send an XPCOM object? MessageChannel.jsm:1009:17
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1065:13
Promise resolved after context unloaded
utils.js:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
Error 9: Key exchange was not successful. keepass.js:1065:13
Failed to connect: Unknown error keepass.js:952:13
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1065:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
Error 9: Key exchange was not successful. keepass.js:1065:13
Failed to connect: Unknown error keepass.js:952:13
Sending message that cannot be cloned. Are you trying to send an XPCOM object? MessageChannel.jsm:1009:17
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1065:13
Promise resolved after context unloaded
utils.js:25
    get moz-extension://cc4eac7a-5858-4fd7-bd05-2fd9159d969d/utils.js:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
Error 9: Key exchange was not successful. keepass.js:1065:13
Failed to connect: Unknown error keepass.js:952:13
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1065:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
Error 9: Key exchange was not successful. keepass.js:1065:13
Failed to connect: Unknown error keepass.js:952:13

**Comment by smorks** [comment]
this appears to be an issue with the latest version of keepassnatmsg-proxy. manually downgrading to 0.0.6 (https://github.com/smorks/keepassnatmsg-proxy/releases/download/v0.0.6/keepassnatmsg-proxy.exe) fixed it for me, until i find the problem with the current version.

**Comment by smorks** [comment]
i just released v0.0.8 of keepassnatmsg-proxy

https://github.com/smorks/keepassnatmsg-proxy/releases/tag/v0.0.8

hopefully that should fix this issue.

**Comment by smorks** [comment]
tested in ubuntu, works. closing issue.

**Comment by GRbit** [comment]
@smorks Please, tell me how to install keepassnatmsg-proxy manually on Linux?
Seems like I have a problem with autoinstall
P.S. sorry for the screenshot, I can't copy text from this window
![image](https://user-images.githubusercontent.com/6090120/131996387-5c16b0e6-6009-42e8-9c68-311d7852568c.png)

**Comment by smorks** [comment]
@GRbit see this issue (#11) for some commands you can try, and there's also instructions to download the proxy manually at the bottom. i will also add instructions to the readme for manually installing the proxy.

**Comment by GRbit** [comment]
Thanks, copying to ~/.keepassnatmsg helps.

P.S. I've tried to make the KeePassXC Firefox plugin work, now it connects to DB, but doesn't request my passwords when I'm loading any page, I don't know why. KeePassHttp-Connector plugin works better.

**Comment by smorks** [comment]
hmmm, that's strange. you're using the latest version of the KeePassXC-Browser? 1.7.9.1 appears to be the latest.

**Comment by GRbit** [comment]
> hmmm, that's strange. you're using the latest version of the KeePassXC-Browser? 1.7.9.1 appears to be the latest.
> 
> also, can you show me what's in the kpnm_firefox.json file in the ~/.keepassnatmsg directory?

Yep. It suggests saving the password after login, correctly saves it to the database, but on logout and page refresh it doesn't fill in my login or password. Tried to set up custom login/pwd fields - it doesn't help either.

**Comment by smorks** [comment]
it could be another extension causing the issue. have you tried disabling all other extensions except for KeePassXC-Browser?

**Comment by GRbit** [comment]
Tried in private mode with only KeePassXC-Browser extension version 1.7.9.1.
I have no kpnm_firefox.json file in the ~/.keepassnatmsg directory.
