### ISSUE TITLE
cannot install with keepass 2.43 (same as #52 with more info)

### ISSUE THREAD

**Issue by zedug** [smorks/keepassnatmsg#55]
- operating system & version: Windows 10 Version 2004  OS build 19041.329
- version of .NET: 4.8
- version of KeePass: v2.43
- version of KeePassNatMsg: v2.0.10
- error message (if available)
![image](https://user-images.githubusercontent.com/9880558/84591067-be771480-ae3b-11ea-851f-dde254e31824.png)
- used clients and their versions: n/a
- URLs on which the problem occur (if available): n/a

I get the above message when starting KeePass after having copied the plugin. And there's no KeePassNatMsg entry in the tools menu.

I did verify my .net installation with the MS diagnostic tool, everything checks out.

**Comment by smorks** [comment]
i compiled against KeePass 2.43, and added it here: https://github.com/smorks/keepassnatmsg/releases/download/v2.0.10/KeePassNatMsg-v2.0.10-keepass-2.43-binaries.zip

hopefully that should work for you.

**Comment by zedug** [comment]
downloaded verified and validated against KP v2.43 and v2.45
thanks a bunch !
