### ISSUE TITLE
Unresponsive banner for saving new or updated credentials. 

### ISSUE THREAD

**Issue by Furocious** [smorks/keepassnatmsg#56]
Thank you for this plug-in and I appreciate that this issue may be as a result of an incompatibility with the Keepass-XC extension.

The "new" and "updated" buttons on the Keepass-XC extension banner for saving new or updated credentials are unresponsive. Only the dismiss button works as intended. As a consequence, credentials are not updated or saved. No matter how much I try (on both Firefox and Chrome), I am unable to save new or updated credentials to the database.

However, this feature works as intended with the old KeePassHttp-Connector extension and I never had an issue with it.

I have tried changing the options for  "Default group for saving new passwords" as well as "Always ask where to save new credentials", with the same outcome. The "new" and "updated" buttons on the banner remain unresponsive when clicked with a mouse.

Thanks.

OS & version: Windows 7 SP1 Ultimate
Version of KeePass: 2.45
Version of KeePassNatMsg: 2.0.10.0, Proxy (0.0.8.40284)
Error message (if available): No error message
Used clients and their versions: Firefox 78.0.1 with Keepass-XC extension 1.6.4, Chrome 83.0.4103.116 Keepass-XC extension 1.6.4
URLs on which the problem occur (if available): All URLs

**Comment by smorks** [comment]
i believe this is the same as #43, and should be fixed in the next release, which is coming soon. i'm just ironing out the last few issues.

**Comment by Furocious** [comment]
> 
> 
> i believe this is the same as #43, and should be fixed in the next release, which is coming soon. i'm just ironing out the last few issues.

Thank you very much.

**Comment by Cy4n1d3** [comment]
I compiled the latest master and can confirm that for me this issue does not occur anymore.
Thanks a lot and keep up the good work 👍

**Comment by smorks** [comment]
@Cy4n1d3 good to hear. i've been meaning to get a new release out with these fixes but been busy lately. i'll try and get an actual release out soon.
