### ISSUE TITLE
Version number of keepass browser not up to date

### ISSUE THREAD

**Issue by agsteele** [smorks/keepassnatmsg#58]
I seem to recall this issue in the past.  I use Keepass (not keepassxc) and have the keepassnatmsg plug-in to connect with the keepass-xc browser add-on with Firefox on a Windows 10 PC.

Recently the Firefox add-on strted to complain that the version number of keepassxc was out of date although I have the most recent versions of both the Firefox add-on and the plugin.

I've been able to fix the nag with the Advanced setting in KeePassNatMsg by setting that to 2.6.0

I seem to recall that this is something you tweak from time to time so just a heads up.

Andrew

**Comment by smorks** [comment]
yes, it's because KeePassXC-Browser checks the version of KeePassXC, so that's why that advanced setting was added, to stop the nagging. Alternatively, you can also turn off version checking in the KeePassXC-Browser settings.

**Comment by agsteele** [comment]
Thanks @smorks The option to turn off version checking doesn't seem to be present.  I'll log it in the relevant place...
