### ISSUE TITLE
Cannot decrypt message

### ISSUE THREAD

**Issue by tfvlrue** [smorks/keepassnatmsg#6]
This bug has been difficult for me to reproduce. Sometimes the keepassxc-browser extension reports this:

![cannotdecrypt](https://user-images.githubusercontent.com/35318734/35255547-a19385c6-ffbd-11e7-9a2d-bdef49fc8a5b.png)

The Reopen button has no effect. KeePass is running and the database is unlocked. The only thing I've found to fix it is restarting Firefox entirely (even disabling/re-enabling the extension had no effect).

This has happened twice so far, and I'm not sure if this is actually a bug with the extension or KeePassNatMsg. What do you think? If I can narrow down repro steps I'll post here.

Thanks,
Luke

**Comment by smorks** [comment]
i've seen this problem too, i'm pretty sure it's not a problem with the extension. i'll do some more digging as well to try and narrow down the problem.

**Comment by smorks** [comment]
i'm able to reliably reproduce this problem by opening another browser, then going back to the first browser. so if i have firefox open & working, i then open chrome, then go back to firefox, and then it gives me the "cannot decrypt" message. i'll keep investigating.

**Comment by tfvlrue** [comment]
Oh, nice catch! I usually use Firefox but occasionally open Chrome. I bet that was doing it.

**Comment by 9strands** [comment]
I'm getting this error message as well.  Firefox and Chrome both open - Firefox first.  Firefox is connected, and Chrome says that it can't decrypt.

**Comment by 9strands** [comment]
Is there something I can do to provide information between chrome and keepass?  I can pull data from chrome, sanitise it, and send it through if that would help @smorks.  I'm just not familiar with chrome's troubleshooting/consoles - which I am for firefox.

**Comment by smorks** [comment]
no, i don't think it's a chrome specific thing. i believe if you started chrome first, it will work until you start firefox. it wasn't designed to handle more than one browser at once, so i just have to figure out how i'm going to handle it.

**Comment by 9strands** [comment]
I can confirm that this fix works for me - I had to open, install the proxies, shut down, re-open, and wait, but then both Firefox and Chrome connected and it seems all good now.

**Comment by tfvlrue** [comment]
Same here. Thanks for the fix!

**Comment by dragoangel** [comment]
KeePassXC-Browser Version: 1.5.1
100% reproduce

**Comment by smorks** [comment]
@dragoangel need more info - what os/browser/keepass/keepassnatmsg versions are you using?

if you haven't already, try closing all your browser windows, then in KeePassNatMsg Options, click on the "Install/Update Native Messaging Host" button, select your browser, and press ok, and try again.

if it's still not working, then open a new issue.

**Comment by sputnick-dev** [comment]
Enabling ssh-agent fixed the issue for me

**Comment by sputnick-dev** [comment]
Enabling `ssh-agent` in the settings, fixed the issue for me

**Comment by Tindalos** [comment]
> Enabling `ssh-agent` in the settings, fixed the issue for me

Also fixed the issue for me, until the next time I restarted my OS.  [Win, Chrome, KeepassXC 2.4.3, KeePassXC-Browser 1.5.1].

If it helps isolate,I've  been using it for perhaps a year and only just started having this happen within the week.

**Comment by Tindalos** [comment]
@smorks Good catch, I'm not!  I found this conversation through a search for the error, and assumed 'KeePassNatMsg' was just some kind of obscure internal program module I hadn't heard of.  Interesting that users are getting this independent of your plugin; hopefully that will help you isolate what's going on for your usersbase.

**Comment by Tindalos** [comment]
@smorks Good catch, I'm not!  I found this conversation through a search for the error, and assumed 'KeePassNatMsg' was just some kind of obscure internal program module I hadn't heard of.  Interesting that users are getting this independent of your plugin; hopefully that will help you isolate what's going on for your usersbase.

**Comment by 9strands** [comment]
I've been using this for over a year, and I've had this kind of thing happen on and off.  When I use either Firefox or Chrome, if I click reload a couple of times, everything starts working.
