### ISSUE TITLE
Add support for Keepass2Android URL fields (KP2A_URL_1, ...)

### ISSUE THREAD

**Issue by gab** [smorks/keepassnatmsg#60]
Keepass2Android has supported extra URL fields for from-filling purposes for a long time. It uses the format KP2A_URL_1, KP2A_URL_2 and so forth.

Would it be possible to use those if found, instead of having to create new fields starting with URL to be recognized by keepassnatmsg?

Perhaps you could simply relax the rule of what the URL fields should be named, and accept them if they contain URL in all caps, not just start with it? (Ideally everyone would be a happy family and KP2A, KeePassNatMsg and KeepassXC would agree on a single format, but it sounds hard to achieve.)

You'd have to parse the URL and make sure to ignore those starting with androidapp://, as those are for filling in forms in apps, not web pages. Probably ignoring any URL root that you can't process (do you process anything beyond http:// or https:// ?) is a good idea.

Thank you!

**Comment by smorks** [comment]
this appears to be the same as #57. closing this one.
