### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by collie9000** [smorks/keepassnatmsg#61]
The basic function of filling passwords stopped working for me since today.
Maybe this is related to the latest update of KeePassXC-Browser 1.7.0 dated 2. September 2020 ?

KeePass v2.45
NatMsg v2.0.10

**Comment by gab** [comment]
Same here, passwords are not getting filled-in anymore. Same versions for KeePass and KeePassNatMsg.

**Comment by smorks** [comment]
i just tested in both Chrome and Firefox on Windows 10, and it appeared to be working for me.

can you tell me which sites you tested?

and also which OS and browser you are running?

**Comment by m0rphU** [comment]
Same here. The login works on no site, including GitHub, Google, etc.

These are my debug information in the KeePassXC Browser plugin:

> KeePassXC - 2.4.3
> KeePassXC-Browser - 1.7.0
> Operating system: Win32
> Browser: Mozilla Firefox 80.0

The browser plugin does also show a hint that I should update KeePassXC?

**Comment by collie9000** [comment]
KeePassXC - 2.4.3
KeePassXC-Browser - 1.7.0
Operating system: Win32
Browser: Chrome/Chromium 85.0.4183.83

**Comment by smorks** [comment]
i'm able to reproduce the issue now. i should hopefully have this fixed soon.

**Comment by smorks** [comment]
please try the new v2.0.11 version. it appears to work better for me.

**Comment by neradp** [comment]
The new version is working fine for me..i had the same problems before.

**Comment by collie9000** [comment]
New Version seems to work better on most sites.

One site, where it is still not working properly for me (it did in the past): https://b2b.dab-bank.de/Tradingcenter/
But as it is also not working with KeePassXC connected, I suspect the error may be with the KeePassXC-Browser Extension.

**Comment by smorks** [comment]
@collie9000 yes, if you're having problems in KeePassXC as well, then it's likely the browser extension. i know they recently updated to version 1.7.1, so give that version a try if you're not running it already?
