### ISSUE TITLE
Cant create new database entry

### ISSUE THREAD

**Issue by michaelcarno** [smorks/keepassnatmsg#62]
KeePassNatMsg 2.0.10.0
KeePass 2.45
KeePassXC-Browser Version: 1.7.0

When you login, KeePassXC-Browser ask you to create new or update entry in db, update works fine, but when you press "New" - nothing. 
1.6.3 -  create/update works fine

**Comment by gab** [comment]
Same here, same software versions.

**Comment by smorks** [comment]
i believe this is the same as #43, and should be fixed in the next release.
