### ISSUE TITLE
Native Messaging Error on Edge-Dev 89.0.752.1

### ISSUE THREAD

**Issue by VinnieNZ** [smorks/keepassnatmsg#67]
After updating Edge-Dev from 89.0.731.0 to 89.0.752.1 KeePassXC Browser seems to stop communicating with KeePassNatMsg correctly.

I've verified in the registry that the entry for the plugin is in Native Messaging Host and checked that the Edge integration and Proxy exist and work.

Reverting the version of Edge-Dev back to 89.0.731.0 fixes the issue.

I've filed a bug with the Edge-Dev team as well.

Error message from the KeePassXC Browser plugin is:
Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1029 Failed to connect: Access to the specified native messaging host is forbidden.

**Comment by smorks** [comment]
my guess is that Edge-Dev maybe changed the registry keys for where things are located? if memory serves correctly, i think it used to use the Chrome registry keys, and maybe they changed that? i'll try and do some investigation and see what i can find out.

**Comment by topia** [comment]
For your information, I verified with Edge-Dev 90.0.782.0, edge-dev refers to Chromium registry key: `HKEY_CURRENT_USER\SOFTWARE\Chromium\NativeMessagingHosts\org.keepassxc.keepassxc_browser`.
So, I can work as expected with:
- installing natmsg-proxy to Chromium
- edit `kpnm_chromium.json` manifest and add `chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/` to `allowed_origins` for KeePassXC-Browser

**Comment by VinnieNZ** [comment]
Awesome find @topia - this worked for me on several different PC's.

**Comment by smorks** [comment]
thanks, @topia! i'll try and get this fixed when i have some free time!

**Comment by Fpadt** [comment]
many Thanks

works still as a charm. I am on 89.0.774.54.
kpnm_chromium.json can be found in C:\Users\<windows_user>\AppData\Local\KeePassNatMsg
