### ISSUE TITLE
  It doesn't work on my computer 

### ISSUE THREAD

**Issue by andeaker** [smorks/keepassnatmsg#78]
KeePass：2.49（64X）
KeePassNatMsg：2.0.13
System: Windows 10 19043.1202
proxy：V2rayN 4.20

Problem:
1. I copy the "keepassnatmsg" folder and all the files in it to the "plugins" directory of KeePass
2. Open "Install / update native messaging host" in keepassnatmsg options

An error message appears: proxy download error
The software seems to conflict with v2rayn.

**Comment by smorks** [comment]
you can download the keepassnatmsg-proxy manually:

1. Download the latest keepassnatmsg-proxy.exe from https://github.com/smorks/keepassnatmsg-proxy/releases
2. Create %LOCALAPPDATA%\KeePassNatMsg folder if it doesn't exist, and copy the keepassnatmsg-proxy.exe to that folder.
3. Go to KeePassNatMsg Options in KeePass, should prompt you to Install the Native Messaging Host, and it should succeed.

**Comment by andeaker** [comment]
I finally confirmed that the previous error was that my proxy was not configured. Now it has been downloaded successfully. Thank you!
