### ISSUE TITLE
Plugin not work with KeePass 2.49

### ISSUE THREAD

**Issue by Ramzzes** [smorks/keepassnatmsg#79]
After update from 2.48.1 version i see this message

![2021-10-03_13-51-06](https://user-images.githubusercontent.com/6473703/135750433-6dc20b9d-6856-458e-b60f-107c90d5736a.jpg)

**Comment by HarHarLinks** [comment]
I am running 2.49 (210914) on Linux, I do not get the above Error, but I do get
> KeePassXC-Browser has encountered an error:
> Message encryption failed. Is KeePassXC running?

**Comment by smorks** [comment]
@Ramzzes hmmm, that's strange, KeePassNatMsg v2.0.13 works fine for me using KeePass 2.49. I'll be putting out a new release soon which will be compiled against KeePass 2.49, so hopefully that should fix the problem.

@HarHarLinks that's also strange, might be a different issue. Are you able to create a new connection at all from the extension? If not, does it help if you click on the "Install/Update Native Messaging Host" button in the KeePassNatMsg options?

**Comment by HarHarLinks** [comment]
I deleted the connection in my browser and were able to create a new one which has worked so far, thanks. I'm not sure what may have caused this.

**Comment by abelcheung** [comment]
I saw the same error under KeePass 2.46. Is it true that any specific version of KeePassNatMsg is compiled against specific KeePass version, and may only work on that specific release?

**Comment by smorks** [comment]
i turns out there was some changes between KeePass 2.46 and 2.49 which cause incompatibilities between versions. i have completed plgx support (which will be available in the next release, due out soon), but from my testing (and what i said earlier) it will won't work with KeePass 2.46.

**Comment by smorks** [comment]
this should be resolved with the latest release, which includes a plgx. i also included a release compiled again keepass 2.45 which should work with some older KeePass versions.
