### ISSUE TITLE
Unable to connect to KeePassXC-Browser

### ISSUE THREAD

**Issue by ligyxy** [smorks/keepassnatmsg#8]
Windows 10
Chrome 64
KeePass 2.38
keepassnatmsg 2.0.0.6
KeePassXC-Browser 1.0.0

After clicking the connect button on KeePassXC-Browser, nothing happens. On the extension debugging page, it shows `Failed to connect: Access to the specified native messaging host is forbidden.`

**Comment by smorks** [comment]
looks like there was a new version publish to the chrome web store that has a new id. i should be able to get it fixed shortly.

**Comment by ligyxy** [comment]
If that's the reason, I think it would be better if you can update the extension link to the official one on README of this repo also.

**Comment by smorks** [comment]
i'll do that too. thanks!

**Comment by ligyxy** [comment]
Still have this issue with v2.0.0-beta.10

**Comment by smorks** [comment]
did you try going to the KeePassNatMsg Options and pressing the Install/Update Native Messaging Host button?

**Comment by ligyxy** [comment]
My mistake, it works. It seems that it just needs a few seconds to connect to db at the first time.
