### ISSUE TITLE
After newest release v2.0.14, all entries prompt

### ISSUE THREAD

**Issue by Skrelpoid** [smorks/keepassnatmsg#84]
It seems these 2 points from the release notes are not quite working as intended:

- security fix: if the title or url fields exactly matched the hostname, without the scheme prefix (ie http, https), it would send the credentials without prompting. this has been changed now to always prompt, if it hasn't already been allowed.

- data is now stored in Custom Data, it will prompt you to move your existing settings when opening a db with data in the legacy location.

After the update the plugin said it migrated my data and told me to delete the entry KeePassHttp Settings from my Database.
After I did that some entries still have KeePassHttp Settings as advanced String fields. I'm not sure but I think on some fields it was removed. However, every page prompts for the credentials and asks me to allow it. After saving it that time everything seems to be working for that entry.

But now for each entry it asks again to allow or disallow the autofill which is kind of annoying.

**Comment by Bond246** [comment]
Hello guys,

i have some strange behavior that maybe is related to this one.
My browsers seems randomly want to reconnect to my database.

And today an idea came to me that evertimes i open the database on a different machine it asks for reconnecting. Could that be?

**Comment by xeropresence** [comment]
I'm still getting this with 2.0.15

I tried to narrow down what's happening using a simple domain : accounts.google.com

On version 2.0.13 visiting accounts.google.com does not prompt for access, all entries are displayed.
Some, but not all of the keepass entries have an additional string field containing ```{"Allow":["https://accounts.google.com"],"Deny":[]}```

After upgrading to 2.0.15

Visiting accounts.google.com prompts for access listing every single account, hitting deny yields no approved entries.
The accounts that had additional string field now have the additional plugin data with the same content of ``{"Allow":["https://accounts.google.com"],"Deny":[]}```

Title for all entries is ```accounts.google.com```
Url for all entries is ```https://accounts.google.com/```

Changing title and/or url has no effect on if account is approved.

If I revisit accounts.google.com and approve the request, and check the box to remember this decision all entries for the site get updated to have the plugin data of ``{"Allow":["accounts.google.com"],"Deny":[]}```

Visiting the site again yields the expected result of the entries just working without a prompt.

If I revert to a backup, and restore 2.0.13, edit the string field setting to ``{"Allow":["accounts.google.com"],"Deny":[]}``` and then upgrade to 2.0.15 the entry that had the edited setting will get approved while all the rest will be rejected when prompted and hitting deny. 

This leads me to believe the issue lies with the change of 
```
security fix: if the title or url fields exactly matched the hostname, without the scheme prefix (ie http, https), it would send the credentials without prompting. this has been changed now to always prompt, if it hasn't already been allowed.```

as the url correctly matches the requesting domain including the scheme and its still requesting additional confirmation.

I don't use any replication or synchronization to a external location.


@smorks if you need anymore information please let me know

**Comment by smorks** [comment]
@xeropresence thanks for the detailed information! i will investigate further with the information you provided, it sounds like that security fix is the likely culprit.

**Comment by xeropresence** [comment]
Prior to version 2.0.14 it wouldn't prompt if the url matched, which is a behavior I expect (and want), but would prompt when accessed from a different subdomain, or when a iframe is used.

https://github.com/smorks/keepassnatmsg/issues/83 Seems to change it to care only about the access list which I think is excessive. I am unsure if the entries are created by the this plugin or if they are created and then just passed thru from KeePassXC-Browser but the default creation does not create an access list (in 2.0.13 at least)

So I am in the current situation where entries that were created by the browser extension no longer work and I must approve their access every time which is cumbersome, and enabling "Always allow access" is undesirable as I do wish to be notified if someone tries to access a sites credentials via iframe or on a subdomain.

I prefer the previous behavior where if a url is supplied then we assume that we want the entry to be sent to the browser.

**Comment by xeropresence** [comment]
> > So I am in the current situation where entries that were created by the browser extension no longer work and I must approve their access every time which is cumbersome, and enabling "Always allow access" is undesirable as I do wish to be notified if someone tries to access a sites credentials via iframe or on a subdomain.
> 
> If you click the "Remember this decision" when allowing access, it will only remember for current domain that you're on. So it should continue to prompt when accessed from subdomains other than the one you "Remembered". Isn't that the behavior you would like?
> 
> so basically, it just required the one extra step of prompting and "Remembering" the domain you would like, and it should continue to prompt on different subdomains/iframes.

Yea, but that's extra work and I like how it worked before. Like you said in the comments to #83 it's how KeePassHttp worked, and I expected the same behavior from this.
Now it's 3 extra clicks, 1 for the checkbox, 1 for the allow, and 1 to refocus the window each time I visit a 
I haven't tested it, but if new entries aren't created with that accesslist then I'll have to do this extra step for each new site and entry as well.

I think #83 should either be reverted and a scheme check added or the change made optional as I don't enjoy the thought of having to approve 500+ sites over time.

**Comment by smorks** [comment]
i would rather just add another option to not prompt if the url is an exact match, which should resolve the issue you have.

i will add an enhancement for that.
