### ISSUE TITLE
Compatibility with Portable Browsers

### ISSUE THREAD

**Issue by hockey6611** [smorks/keepassnatmsg#90]
Is keepassnatmsg compatible (or can it be made to be compatible) with portable browsers? I have seen some references in issues of use of portable KeePass, but not a portable browser. I am currently running KeePass portable, and Firefox ([portable apps](https://portableapps.com/apps/internet/firefox_portable)), as a non-administrator user.

I have successfully set up the plugin and extension on another machine, with both browser and KeePass installed, with no issues.

While using the portable versions, I am able to "install" native messaging host with the plugin, within KeePass. The install is noted as successful in the plugin menu. However, ultimately, when I attempt to connect the database within Firefox KeePassXC-Browser, nothing happens. There is no visual response to the button press.

I am presuming that since the browser is portable, the install of native messaging host doesn't know where the browser profile/root is. I am hoping there is a manual way these can be connected, but I haven't found what that would be yet searching through repository and documentation.

**Comment by smorks** [comment]
I will test with portable Firefox to see if I can reproduce the problem.

**Comment by hockey6611** [comment]
Greatly appreciate you taking a look. Am I understanding correctly that use of registry keys is necessary for native messaging, in normal use case? In that case portable browser may have inherent incompatibilities, since (I think) registry is not used.

Searching across the web I found this [unanswered forum post on portableapps.com](https://portableapps.com/node/61454) asking about a different native messaging project.

I also found [this project issue](https://github.com/dessant/buster/issues/222) that uses native messaging, and the developer states registry entry is required.

**Comment by smorks** [comment]
yes, i believe registry keys are necessary for native messaging.

**Comment by smorks** [comment]
i was able to get it working successfully with the portable apps version, it still uses the same registry key that regular firefox uses, from what i can tell.

i would make sure that portable firefox is the only firefox running, and maybe try with KeePassXC-Browser as the only add-on? i'm not sure what else might be causing the issue.

**Comment by hockey6611** [comment]
I appreciate you looking at this. Yes portable firefox is the only version of firefox running.

I dug into it further. It appears the registry keys are in my system, so I'd say that is likely not the issue. When I run the `keepassnatmsg-proxy.exe` program directly from `C:\Users\user1\AppData\Local\KeePassNatMsg`, I receive the error:

> This app has been blocked by your system administrator.
> Contact your system administrator for more info.
> ![image](https://user-images.githubusercontent.com/28613898/158722167-61d97d8c-d990-4a1c-b045-0a8d2ad527cc.png)

I am not sure, but I think I am receiving this error because the executable is [not signed](https://www.virustotal.com/gui/file/73ba4f3ff0b8696d9c1e173967a7dbb6a96680b3267ff3db0f3dc8a8a36f8188/details#:~:text=keepassnatmsg%2Dproxy.exe-,Signature%20Info,-Signature%20Verification). When the plugin utilizes it, it probably fails silently, and that would match the symptoms I am having.

I stumbled onto this possible explanation while testing portapps.io's [Phyrox portable](https://portapps.io/app/phyrox-portable/). The executable provided is similarly unsigned and I receive the same message. Portable apps executables, however, are signed. Both [PortableApps.com setup](https://www.virustotal.com/gui/file/9a78b58bd0cd2612ae0373e74056b75722b87601b6770ec1a34e28d128b84cbc/details#:~:text=Firefox%2C%20Portable%20Edition-,Signature%20Info,-Signature%20Verification) and [Firefox Portable itself](https://www.virustotal.com/gui/file/c7bb130fd64f26ecb6893bb95a8971bdb64c49494bae610019fd82e6236a27c1/details#:~:text=firefoxportable.exe-,Signature%20Info,-Signature%20Verification) as signed, as well as [Keepass portable](https://www.virustotal.com/gui/file/1692d1bc1d95c27be004fce4a13e946cd7b2c3769948a971ed0e662a27b97997/details#:~:text=KeePass.exe%20(copy)-,Signature%20Info,-Signature%20Verification). So in using these previously, I had not run into this issue.

Does this seem like a likely explanation to you? I am running portable because I do not manage the machine (group policy managed), and am a non-administrator. I presume I am restricted from running any unsigned executable. Unfortunately, I am unable to change this. Is there any possibility to sign the executable in the future? I know this can be a large hurdle though.

It works wonderfully on my personal machine, where I don't have any of these issues. Thank you for this great software.

**Comment by hockey6611** [comment]
I certainly appreciate that this is an edge case, and thank you for the troubleshooting assistance.

**Comment by sergeevabc** [comment]
I doubt whether it is worth opening a new topic, as my question concerns the portability, which is not at all obvious in the case of Keepassnatmsg. This plugin is positioned as a step above KeePassHttp, but is it fair to say so?

Externally, they are similar, but under the hood `keepassnatmsg-proxy.exe` is planted to the user's profile and the registry is polluted. Thus, Keepass app ceases to be portable, and the system on which it runs turns out to have traces of use. 

Do the developers think about this?

**Comment by smorks** [comment]
> I doubt whether it is worth opening a new topic, as my question concerns the portability, which is not at all obvious in the case of Keepassnatmsg. This plugin is positioned as a step above KeePassHttp, but is it fair to say so?
> 
> Externally, they are similar, but under the hood `keepassnatmsg-proxy.exe` is planted to the user's profile and the registry is polluted. Thus, Keepass app ceases to be portable, and the system on which it runs turns out to have traces of use.

the `keepassnatmsg-proxy.exe` could potentially be in a different spot for portable users. however, i'm not sure if there's a way around the registry entries, since those appear to be required for the browsers to communicate via Native Messaging. see here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

**Comment by sergeevabc** [comment]
@smorks, what's the proper way to uninstall it?

**Comment by smorks** [comment]
> @smorks, what's the proper way to uninstall it?

the only way to uninstall currently is to remove the `KeePassNatMsg` folder in `%LOCALAPPDATA%` and manually removing the registry entries.
