### ISSUE TITLE
KeePassXC-Browser won't stay connected

### ISSUE THREAD

**Issue by HarHarLinks** [smorks/keepassnatmsg#91]
For a couple weeks now, whenever I try to use the browser extension to fill my passwords, it isn't connected. I click reconnect, then it goes into a state as if it never has been connected. Then I create a new connection and it works.
The next day, I have to repeat these steps.

Keepass 1.50 (220209)
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Chrome/Chromium 98.0.4758.88

**Comment by smorks** [comment]
I thought it should at least mark the database as having changes, so when you close it should prompt to save changes. I will test and see what if I can reproduce.

**Comment by HarHarLinks** [comment]
I had my keepass set to autosave when locking and autolock after timeout, yet it never got saved :/

**Comment by smorks** [comment]
i confirmed the issue. will look into it more when i have some free time.

**Comment by smorks** [comment]
duplicate of #85, closing this issue.
