### ISSUE TITLE
KeepassXC Browser Plugin complaining about old version

### ISSUE THREAD

**Issue by clst** [smorks/keepassnatmsg#93]
Looks like some version number has changed.

The Firefox Addon now shows this warning:

> You are using an old version of KeePassXC.
[Please download the latest version from keepassxc.org](https://keepassxc.org/download).

**Comment by smorks** [comment]
whenever i do a new release i typically update the version # to match whatever the latest release off KeePassXC is.

also, there's an option (`KeePassXC Version Override`) under the Advanced tab of the KeePassNatMsg options to override the version returned, so it stops nagging you. Or you can just turn off version checking in KeePassXC-Browser.
